# Generated by Django 4.1.3 on 2023-01-10 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='ano_del_carro',
        ),
    ]
